### ISSUE TITLE
kotlinx.serialization support

### ISSUE THREAD

**Issue by Shengaero** [Litote/kmongo#104]
Would be great to see some native support for [kotlinx.serialization](https://github.com/Kotlin/kotlinx.serialization)!

**Comment by jershell** [comment]
Do you have whatever news?

**Comment by zigzago** [comment]
No progress. I have no real use case for my own apps, and as kotlinx serialization is still marked as experimental, this is currently not a high priority for me.

Of course it would be great to use kotlinx instead of jackson or pojo. Performance will be better without reflection. 

Also, it would be great to have a java/js/native plugin to manage bson serialization.

**Comment by jershell** [comment]
I try to implement it. Now ready simple [adapter](https://github.com/jershell/kbson) org.bson.BsonDocument <->  Kotlin data class by kotlin.serilization.

**Comment by zigzago** [comment]
@jershell  nice :) I'm going to take a look

**Comment by jershell** [comment]
Today kotlinx.serialization project approves and publish my extension. Now we can use the bson format with kotlinx.serialization https://github.com/Kotlin/kotlinx.serialization/tree/master/formats

**Comment by zigzago** [comment]
Very nice. :) I will try to add it to KMongo this week.
