### ISSUE TITLE
Complicated aggregate with group on array of Ids

### ISSUE THREAD

**Issue by robert-cronin** [Litote/kmongo#125]
I'm not sure if this is documented anywhere, just point me in that direction if it is.
I have got 2 collections, Fleet and Aircraft. There is a list of Aircraft Ids in Fleet:
```
data class Aircraft(var _id:Id<Aircraft> = newId(), ...)
data class Fleet(var _id:Id<Fleet> = newId(),
                 var aircraft_id_list:MutableList<Id<Aircraft>> = mutableListOf(),
                 ....)
```
 I would like aggregate this list of ids into actual aircraft objects and then project only a couple of fields in Aircraft.
How would I go about doing this with the Aggregation pipeline?
This is what I've tried so far:
```
val fleetList = fleetCollection
        .aggregate(
                unwind("aircraft_id_list"),
                lookup("aircraft",
                        "aircraft_id_list",
                        "_id",
                        "aircraft"
                ),
                unwind("aircraft"),
                group(
                        "_id",
                        pushEach(Fleet::aircraft_id_list)
                ),
                project(Aircraft::_id, Aircraft::registration)
        )
        .toMutableList()
```
But I am getting an error on `group` telling me it's looking for `List<BsonField>`
Let me know if there's an easy way to do this, otherwise I can also just do it in two find queries. Cheers!

**Comment by zigzago** [comment]
Please use [gitter](https://gitter.im/kmongoo/Lobby?) or [the dedicated google group](https://groups.google.com/forum/#!forum/kmongo) for this kind of question.

You have to specify the type of the result:

```kotlin
data class Result(val _id:Id<Aircraft>, val registration:String)

val fleetList = fleetCollection.aggregate<Result>(
or
val fleetList : MutableList<Result> = fleetCollection.aggregate( 
```
Here is the doc: http://litote.org/kmongo/extensions-overview/#aggregate

But the real issue is that you use the Update push operator : https://docs.mongodb.com/manual/reference/operator/update/push/ instead of the aggregate one https://docs.mongodb.com/manual/reference/operator/aggregation/push

Two options:

1) Write the bson directly:

```kotlin
...
unwind("aircraft"),
"{\$group:{_id:\"\$_id\",registration:{\$push:"\$aircraft_id_list\"}}}".bson,
...
```
2) Use typed query (better!):
```kotlin
...
unwind("aircraft"),
group(Aircraft::_id, Aircraft::registration.push(Fleet::aircraft_id_list)),
...
```
HTH
