### ISSUE TITLE
Jackson code works incorrect with float values inside arrayList

### ISSUE THREAD

**Issue by SouthOfWest** [Litote/kmongo#133]
RawBsonDocumentCodecs used in such situation. 
Instead of save 12.3 we have 12.30000019073486

`    "Packages" : [ 
        {
            "Dimensions" : {
                "UOM" : "IN",
                "Height" : 1.5,
                "Width" : 12.30000019073486,
                "Length" : 3.0
            },
            "Weights" : {
                "UOM" : "PG",
                "Weight" : 2.5
            }
        }, 
        {}
    ]`

As I understand the only solution to write my codec which is to use completely instead of JacksonCode. Correct me if I wrong, please

**Comment by zigzago** [comment]
@SouthOfWest You are right, MongoDb (and Bson) does not support float values. So before inserting floats, Bson4Jackson cast them to doubles. And `println(12.3F.toDouble())` is printing `12.30000019073486`...

The best solution is to replace your float typed properties by double typed properties. Or better, use BigDecimal...

If you can't modify your data classes, you can use a custom codec for the Dimensions class in order to store the float in MongoDb as String or as BigDecimal. 

Definitely not a KMongo's bug ;)

HTH
