### ISSUE TITLE
Some words about transactions

### ISSUE THREAD

**Issue by otbe** [Litote/kmongo#146]
Hi 

I would like to use kmongo for my next kotlin/mongo project but Im a little bit concerned about mongo transactions. Is there any programmatic support? Couldn't find something in the docs. 

Thank you 😊

**Comment by zigzago** [comment]
KMongo uses under the hood  the java driver, so KMongo supports transactions ;)

Also, you can see that all extensions have a version with the ClientSession parameter, required to support transactions : http://litote.org/kmongo/dokka/kmongo/org.litote.kmongo/com.mongodb.client.-mongo-collection/index.html

It would be nice to include a sample in the doc, in order to explain how to write transaction code in kotlin - will add it in the next version. 

Meanwhile, you can look at the reference page that contains a java sample: https://docs.mongodb.com/manual/core/transactions/

HTH

**Comment by otbe** [comment]
That makes sense. Thank you very much 👍
