### ISSUE TITLE
Filter field as Id object is not generated as ObjectId

### ISSUE THREAD

**Issue by ronjunevaldoz** [Litote/kmongo#328]
## Issue
Using user to a filter causes a wrong value return `String` instead of `ObjectId` as JSON.

## Sample Code

```kotlin
// Sample Filter
(UserSubscription::user eq userId.toId()).json
// Actual
{ user: "<id_here>"}
// Expectation
{ user :  ObjectId("<id_here>") }

// data class
@Serializable
data class UserSubscription(
    @SerialName("_id")
    @Contextual val id: Id<UserSubscription> = newId(),
    @Contextual val user : Id<User>
)
```

## MongoDB sample data
![image](https://user-images.githubusercontent.com/4947998/156998162-df687aea-d4da-473a-a304-95ea5fd253c5.png)

**Comment by zigzago** [comment]
This is WAD

You need to write 

`(UserSubscription::user eq ObjectIf("6244ba8b131ffc0267c9a10c").toId()).json`

print -> 

`{"user": {"$oid": "6244ba8b131ffc0267c9a10c"}}`

This is because KMongo does not use the left operand type to transform the Id type (it would be doable for eq operator, but not for more complex operators - so we are consistent)

HTH

**Comment by ronjunevaldoz** [comment]
> This is WAD
> 
> You need to write
> 
> `(UserSubscription::user eq ObjectIf("6244ba8b131ffc0267c9a10c").toId()).json`
> 
> print ->
> 
> `{"user": {"$oid": "6244ba8b131ffc0267c9a10c"}}`
> 
> This is because KMongo does not use the left operand type to transform the Id type (it would be doable for eq operator, but not for more complex operators - so we are consistent)
> 
> HTH

`ObjectIf` does not exists in the library?

**Comment by zigzago** [comment]
Sorry there is a typo:

ObjectI**d**
