### ISSUE TITLE
BigDecimal persisting

### ISSUE THREAD

**Issue by Restless-Anchoret** [Litote/kmongo#43]
The problem is that when an entity class contains a field of BigDecimal type, it is persisted into the database with a field of Double type, but it should be Decimal type (from MongoDB 3.4 version). If the standard MongoDB driver is used, without KMongo, BigDecimal is persisted with a field of Decimal type, so the problem is only in KMongo.
Please, fix it.

**Comment by zigzago** [comment]
The problem is not really in KMongo but in bson4jackson ( https://www.michel-kraemer.com/binary-json-with-bson4jackson/ ) that KMongo uses under the hood. Bson4Jackson does not support Decimal types.

As I've already done a fork of bson4jackson, I'm going to commit a fix on 3.6, but it will take some time.

As a workaround, you can switch to **kmongo-native** that is already ok (see http://litote.org/kmongo/#object_mapping_mode for explanation & [Advanced usage section](http://litote.org/kmongo/#usage) to know how to add the dependency )

Unit test  is here : https://github.com/Litote/kmongo/blob/master/kmongo-core-tests/src/main/kotlin/org/litote/kmongo/BigDecimalTest.kt
