### ISSUE TITLE
Jackson's ObjectNode class serialized as Array

### ISSUE THREAD

**Issue by pplcf** [Litote/kmongo#51]
Whenever you pass ObjectNode as value for update/findAndUpdate it gets serialized as array.

    val objectNode : ObjectNode = jacksonObjectMapper().createObjectNode()
    objectNode.put("test", 123)
    database.getCollection("test").updateOne(Filters.eq("_id", "test"), Updates.set("objectField", objectNode), UpdateOptions().upsert(true))

results in `{ "_id" : "test", "objectField" : [ [ ] ] }`

**Comment by zigzago** [comment]
I think that it would be a mistake for KMongo to support serialization of an "internal" class like ObjectNode. It would be difficult because  ObjectNode implements Iterable (and this is why you get an empty array), so KMongo would need to override default CodecRegistry behaviour (that can be customized by the user).

If you can, use maps. If you really need to use ObjectNode, instead of:

```kotlin
 Updates.set("objectField", objectNode)
```

 you can write  

```kotlin
 Updates.set("objectField" , mapper.convertValue(objectNode, Map::class.java))
```
And it will work.
I'm going to commit a UT to demonstrate the case and close the issue.
