### ISSUE TITLE
How to receive Set<ObjectId> in mongoDb to List<String> in model?

### ISSUE THREAD

**Issue by KasemJaffer** [Litote/kmongo#96]
I have a collection in mongodb that has a field of type ```Set<ObjectId>```. 

When i do query, that field is not mapped correctly to ```List<String>```.

I get
```
 [
"de.undercouch.bson4jackson.types.ObjectId@57fbc06f", 
"de.undercouch.bson4jackson.types.ObjectId@57fbc07f"
]
```

Instead of list of objectId in hexString
```
 [
"57cf0b8e497e002455dcfa88", 
"87cf0b8e497e002455dcfa88"
]
```

Is there a way to receive array of ObjectIds as array of hexString?

Thank you

**Comment by zigzago** [comment]
Hello,

The lib bson4jackson is using a String.valueOf method when parsing a String (see https://github.com/michel-kraemer/bson4jackson/blob/master/src/main/java/de/undercouch/bson4jackson/BsonParser.java#L692 ). That's why you get the result of the de.undercouch.bson4jackson.types.ObjectId.toString() call.

You have two "quick fix" options.

1) Declare a list of ObjectIds or Ids in your class and map the list of Strings in a delegated property:

```
data class Data(val ids:List<org.bson.types.ObjectId>) {
@get:Transient 
val stringIds:List<String> get() = ids.map{it.toString()}
}
```

or 

```
data class Data(val ids:List<Id<Any>>) {
@get:Transient 
val stringIds:List<String> get() = ids.map{it.toString()}
}
```

2) Write a custom jackson deserializer for the class.

Also, as it is nice feature, I've just added default support for this kind of collection mapping. The fix is in the snapshot and will be in the next release.

HTH
